FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y \
  curl bash build-essential sudo git jq openjdk-8-jdk unzip

ENV PATH "$PATH:~/.cargo/bin"

################################## INTELLIJ ####################################
COPY intellij.tar.gz /tmp/intellij.tar.gz

RUN mkdir /opt/intellij

RUN tar -xzf /tmp/intellij.tar.gz -C /opt/intellij --strip 1 && \
      rm -f /tmp/intellij.tar.gz

COPY docker-files/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
